version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-app
    volumes:
      - ./php:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    env_file:
      - .env
    environment:
      - TZ=Europe/Paris

volumes:
  sqlserver_data:
    name: sqlserver_data